title: "Commune is Real"
description: "A community project driven by sustainable practices and a conscious lifestyle. Our motives include awareness of climate change, increasing a connection with our food and shelter and living a minimal, sustainable life."
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
 noscript: false
kramdown:
 math_engine: mathjax
 input: GFM
 hard_wrap: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
permalink: pretty
